export default {
  APP_START: 'APP_START',
  SET_SLIDE_COUNT: 'SET_SLIDE_COUNT',
  UPDATE_ACTVE_SLIDE: 'UPDATE_ACTVE_SLIDE',
  UPDATE_CURSOR_STATUS: 'UPDATE_CURSOR_STATUS',
  UPDATE_MENU_STATUS: 'UPDATE_MENU_STATUS',
};
